-- ============================================================
-- Albatros: categorie configurabili dal Configuratore, al posto di quelle fisse.
-- Da eseguire nell'SQL Editor di Supabase, dopo sql/albatros.sql.
--
-- La prima versione di albatros.sql scriveva la categoria come testo in albatros_listino e
-- albatros_spese, con valori decisi dall'app. Ora le categorie stanno in albatros_categorie e
-- voci e spese le citano per id. Le categorie gia' assegnate si convertono: campi e feste
-- restano tali, tutto il resto del listino va in Bar; le spese tengono la loro.
--
-- Ripetibile: su un database gia' migrato, o creato dalla versione nuova di albatros.sql, non
-- cambia niente.
-- ============================================================

begin;
set local lock_timeout = '3s';

create table if not exists albatros_categorie (
  id bigint generated by default as identity primary key,
  tipo text not null check (tipo in ('listino', 'spesa')),
  nome text not null check (btrim(nome) <> ''),
  ordine integer not null default 0,
  attiva boolean not null default true,
  creato_il timestamptz not null default now()
);
create unique index if not exists albatros_categorie_nome_idx on albatros_categorie (tipo, lower(btrim(nome)));

insert into albatros_categorie (tipo, nome, ordine)
values ('listino', 'Campi', 1), ('listino', 'Feste', 2), ('listino', 'Bar', 3),
       ('spesa', 'Spesa bar', 1), ('spesa', 'Pulizia', 2), ('spesa', 'Manutenzione', 3),
       ('spesa', 'Utenze', 4), ('spesa', 'Compensi', 5), ('spesa', 'Altro', 6)
on conflict do nothing;

alter table albatros_listino add column if not exists categoria_id bigint references albatros_categorie(id) on delete restrict;
alter table albatros_spese add column if not exists categoria_id bigint references albatros_categorie(id) on delete restrict;

-- Conversione dalla vecchia colonna testo, solo se c'e' ancora.
do $$
begin
  if exists (select 1 from information_schema.columns where table_name = 'albatros_listino' and column_name = 'categoria') then
    update albatros_listino l
       set categoria_id = c.id
      from albatros_categorie c
     where c.tipo = 'listino' and l.categoria_id is null
       and c.nome = case l.categoria when 'campi' then 'Campi' when 'feste' then 'Feste' else 'Bar' end;
    alter table albatros_listino drop column categoria;
  end if;

  if exists (select 1 from information_schema.columns where table_name = 'albatros_spese' and column_name = 'categoria') then
    update albatros_spese s
       set categoria_id = c.id
      from albatros_categorie c
     where c.tipo = 'spesa' and s.categoria_id is null
       and c.nome = case s.categoria
                      when 'spesa_bar' then 'Spesa bar' when 'pulizia' then 'Pulizia'
                      when 'manutenzione' then 'Manutenzione' when 'utenze' then 'Utenze'
                      when 'compensi' then 'Compensi' else 'Altro' end;
    alter table albatros_spese drop column categoria;
  end if;
end $$;

alter table albatros_categorie disable row level security;

commit;

-- Controllo: categorie create, e nessuna voce o spesa rimasta senza categoria.
select
  (select count(*) from albatros_categorie) as categorie,
  (select count(*) from albatros_listino where categoria_id is null) as voci_senza_categoria,
  (select count(*) from albatros_spese where categoria_id is null) as spese_senza_categoria;
