-- ============================================================
-- Modulo Albatros: chiusure di cassa, spese e listino del centro sportivo.
-- Da eseguire nell'SQL Editor di Supabase.
--
-- Ogni sera si chiude la cassa (POS e contanti contati, la cassa si svuota ogni sera) e, se si
-- ha tempo, si spiega com'e' composto l'incassato con righe del listino: 20 caffe' a 1 euro,
-- 2 ore di campo a 55. Il listino non si compila a tavolino: nasce dalle voci che si scrivono
-- nelle chiusure.
--
-- L'incassato della giornata e' POS + contanti contati. Le spese si registrano a parte e non
-- entrano nella chiusura.
--
-- Una chiusura con chiusa_il valorizzato ha POS e contanti bloccati (la composizione resta
-- aperta): per correggerli l'amministratore riapre la giornata. I ragazzi possono solo
-- aggiungere; correggere e togliere spetta all'amministratore. Come nel resto dell'app questi
-- blocchi li applica l'interfaccia, non il database.
-- ============================================================

begin;
set local lock_timeout = '3s';

-- Le categorie si decidono dal Configuratore, non sono fisse: una tabella sola per quelle del
-- listino (da dove arriva l'incasso) e quelle delle spese, distinte da "tipo". Una categoria
-- usata non si cancella (il passato la cita): si archivia, e sparisce dalle scelte.
create table if not exists albatros_categorie (
  id bigint generated by default as identity primary key,
  tipo text not null check (tipo in ('listino', 'spesa')),
  nome text not null check (btrim(nome) <> ''),
  ordine integer not null default 0,
  attiva boolean not null default true,
  icona text,                                -- chiave di src/moduli/albatros/iconeCategoria.js
  creato_il timestamptz not null default now()
);
create unique index if not exists albatros_categorie_nome_idx on albatros_categorie (tipo, lower(btrim(nome)));

-- Categorie di partenza, poi si cambiano dal Configuratore. Ripetibile senza duplicare.
insert into albatros_categorie (tipo, nome, ordine, icona)
values ('listino', 'Campi', 1, 'pallone'), ('listino', 'Feste', 2, 'festa'), ('listino', 'Bar', 3, 'bar'),
       ('spesa', 'Spesa bar', 1, null), ('spesa', 'Pulizia', 2, null), ('spesa', 'Manutenzione', 3, null),
       ('spesa', 'Utenze', 4, null), ('spesa', 'Compensi', 5, null), ('spesa', 'Altro', 6, null)
on conflict do nothing;

-- Il listino del centro. Prezzo e' il
-- prezzo standard proposto: sulla riga di una chiusura si puo' cambiare (tariffe riservate).
-- Una voce archiviata (attiva = false) sparisce dalla griglia e dai suggerimenti.
create table if not exists albatros_listino (
  id bigint generated by default as identity primary key,
  nome text not null check (btrim(nome) <> ''),
  categoria_id bigint references albatros_categorie(id) on delete restrict,   -- null = senza categoria
  prezzo numeric(10,2) not null default 0 check (prezzo >= 0),
  attiva boolean not null default true,
  creato_il timestamptz not null default now(),
  creato_da bigint references utenti(id) on update cascade on delete set null
);
-- "Caffe" e "caffe " sono la stessa voce: senza questo vincolo il listino si riempie di doppioni.
create unique index if not exists albatros_listino_nome_idx on albatros_listino (lower(btrim(nome)));

-- Una chiusura per giorno.
create table if not exists albatros_chiusure (
  id bigint generated by default as identity primary key,
  data date not null unique,
  pos numeric(10,2) check (pos >= 0),                -- null = non ancora scritto
  contanti numeric(10,2) check (contanti >= 0),      -- null = non ancora contati
  chiusa_il timestamptz,                     -- null = giornata ancora aperta
  chiusa_da bigint references utenti(id) on update cascade on delete set null,
  creato_il timestamptz not null default now(),
  creato_da bigint references utenti(id) on update cascade on delete set null
);

-- Composizione dell'incassato. Il prezzo e' copiato sulla riga: cambiare il listino non
-- riscrive il passato. La voce non si cancella finche' ha righe (si archivia o si unisce).
create table if not exists albatros_righe (
  id bigint generated by default as identity primary key,
  chiusura_id bigint not null references albatros_chiusure(id) on delete cascade,
  voce_id bigint not null references albatros_listino(id) on delete restrict,
  quantita numeric(10,2) not null default 1 check (quantita > 0),
  prezzo numeric(10,2) not null check (prezzo >= 0),
  creato_il timestamptz not null default now(),
  creato_da bigint references utenti(id) on update cascade on delete set null
);
create index if not exists albatros_righe_chiusura_idx on albatros_righe (chiusura_id);
create index if not exists albatros_righe_voce_idx on albatros_righe (voce_id);

-- Le uscite. Le paga uno degli enti elencati nell'app (albatros, bfm, lama).
create table if not exists albatros_spese (
  id bigint generated by default as identity primary key,
  data date not null,
  importo numeric(10,2) not null check (importo > 0),
  descrizione text not null check (btrim(descrizione) <> ''),
  categoria_id bigint references albatros_categorie(id) on delete restrict,
  ente text not null default 'albatros',
  creato_il timestamptz not null default now(),
  creato_da bigint references utenti(id) on update cascade on delete set null
);
create index if not exists albatros_spese_data_idx on albatros_spese (data);

-- Come le altre tabelle dell'app: la chiave anon deve poterle leggere e scrivere.
alter table albatros_categorie disable row level security;
alter table albatros_listino disable row level security;
alter table albatros_chiusure disable row level security;
alter table albatros_righe disable row level security;
alter table albatros_spese disable row level security;

commit;

-- Controllo: le tabelle ci sono.
select
  (select count(*) from albatros_categorie) as categorie,
  (select count(*) from albatros_listino) as listino,
  (select count(*) from albatros_chiusure) as chiusure,
  (select count(*) from albatros_righe) as righe,
  (select count(*) from albatros_spese) as spese;
