-- ============================================================
-- Catalogo giochi — fase 1.
-- Da eseguire nell'SQL Editor di Supabase.
--
-- Oggi il "gioco" non esiste come cosa a sé: sta nascosto in due elenchi diversi che non si
-- conoscono. Nel nome del gonfiabile, dove la stessa struttura compare una volta per sede
-- (Calcio Balilla Umano quattro volte, quattro fornitori, quattro prezzi). E nel nome del
-- pacchetto di prenotazione, dove "Bubble Party Basic" tiene insieme la modalità e il gioco.
-- È il motivo per cui non si può chiedere quanto ha reso l'Archery: la domanda non ha un
-- soggetto a cui appoggiarsi.
--
-- Questa migrazione crea quel soggetto e ci aggancia i due elenchi.
--
-- NON TOGLIE E NON RISCRIVE NIENTE. Le due colonne nuove nascono nulle e l'applicazione che
-- gira in questo momento le ignora: si può eseguire con gli utenti al lavoro, e annullarla
-- vorrebbe dire semplicemente smettere di leggerle.
--
-- È RIESEGUIBILE: ogni passo agisce solo dove il dato manca ancora, e il catalogo già creato
-- non viene toccato. Va rilanciata dopo aver messo online le tendine di scelta del gioco, per
-- raccogliere le righe inserite nel frattempo.
--
-- Sulle maiuscole: la tabella nuova usa snake_case come le altre tabelle recenti (op_voci,
-- disp_calendario, compensi_parametri); le colonne aggiunte a "gonfiabili" e "prenotazioni"
-- usano il camelCase di quelle tabelle. Ogni tabella resta coerente con se stessa.
-- ============================================================

-- ------------------------------------------------------------
-- 0) PRIMA — la fotografia da cui si parte. Attesi: 28 nomi distinti di gonfiabile su 39 righe,
--    35 prenotazioni su 6 nomi di pacchetto, 2 delle quali con un preventivo collegato.
-- ------------------------------------------------------------
select 'nomi distinti di gonfiabile' as cosa, count(distinct nome)::text as quanti from gonfiabili
union all select 'righe di gonfiabile', count(*)::text from gonfiabili
union all select 'prenotazioni', count(*)::text from prenotazioni
union all select 'prenotazioni con preventivo', count(*)::text from prenotazioni where "preventivoCollegato" is not null;

begin;

-- Rete di sicurezza per l'esecuzione a utenti collegati. Aggiungere una colonna richiede per un
-- istante un lock esclusivo sulla tabella: se in quel momento qualcosa la sta tenendo occupata,
-- senza questo timeout la migrazione si metterebbe in coda — e dietro di lei si accoderebbero
-- tutte le letture, bloccando l'applicazione finché non si libera. Con il timeout, dopo tre
-- secondi rinuncia e annulla tutto: meglio riprovare fra un minuto che fermare qualcuno.
set local lock_timeout = '3s';

-- ------------------------------------------------------------
-- 1) LA TABELLA.
--
-- Il nome è unico perché è la chiave con cui il gioco si riconosce a occhio, e perché nelle
-- fasi successive il preventivatore continuerà a raggruppare per nome: due giochi omonimi lo
-- farebbero sbagliare in silenzio. Il database lo impedisce, così non dipende dall'attenzione.
--
-- famiglia e centro_ricavo restano testo libero, come "centroRicavo" e "centroCosto" che già
-- esistono su pacchetti e campi. Nascono vuoti: li compili tu dal modulo Catalogo, perché è
-- una decisione tua (Biliardino 1vs1..11vs11 sono sei giochi di una famiglia sola, e questo
-- lo sai tu, non lo può dedurre una query).
--
-- per_pacchetti dice se il gioco si può scegliere su un pacchetto a location dai campi.
-- attivo serve a togliere dalle tendine un gioco che non si usa più, senza cancellarlo:
-- le righe storiche continuano a puntarci.
-- ------------------------------------------------------------
create table if not exists giochi (
  id bigint generated by default as identity primary key,
  nome text not null unique,
  famiglia text,
  centro_ricavo text,
  per_pacchetti boolean not null default false,
  attivo boolean not null default true,
  creato_il timestamptz not null default now()
);

-- ------------------------------------------------------------
-- 2) IL CATALOGO SI POPOLA DA SÉ, dai nomi che hai già in anagrafica gonfiabili.
--
-- per_pacchetti si accende dove il gioco esiste presso una sede di proprietà: un pacchetto
-- da campo parte sempre da BFM, quindi un gioco che lì non c'è non è proponibile. Oggi
-- accende Bubble Football, Dark Soccer e Archery Tag, che sono esattamente i tre giocabili.
--
-- "on conflict do nothing" è quello che rende innocua la riesecuzione: un gioco già a
-- catalogo non viene ritoccato, e le famiglie e i centri che avrai compilato restano tuoi.
-- ------------------------------------------------------------
insert into giochi (nome, per_pacchetti)
select distinct
       g.nome,
       exists (select 1 from gonfiabili x join sedi s on s.id = x."locationId"
                where x.nome = g.nome and s.bfm)
  from gonfiabili g
 where coalesce(g.nome, '') <> ''
on conflict (nome) do nothing;

-- ------------------------------------------------------------
-- 3) I GONFIABILI PUNTANO AL LORO GIOCO.
--
-- La colonna nasce nulla e nessuno la legge: il preventivatore continua a lavorare sul nome
-- esattamente come prima. Serve a rendere sommabili le quattro righe di Calcio Balilla Umano,
-- che oggi sono quattro cose diverse per chiunque le guardi da fuori.
-- ------------------------------------------------------------
alter table gonfiabili add column if not exists "giocoId" bigint;

update gonfiabili g
   set "giocoId" = j.id
  from giochi j
 where j.nome = g.nome
   and g."giocoId" is null;

alter table gonfiabili drop constraint if exists gonfiabili_gioco_fk;
alter table gonfiabili add  constraint gonfiabili_gioco_fk
  foreign key ("giocoId") references giochi(id) on update cascade on delete restrict;

create index if not exists gonfiabili_gioco_idx on gonfiabili ("giocoId");

-- ------------------------------------------------------------
-- 4) LE PRENOTAZIONI PUNTANO AL LORO GIOCO.
--
-- Due strade, nell'ordine. Prima quella certa: se c'è un preventivo collegato, il gioco è
-- scritto nelle sue righe con tanto di "gonfiabileId", quindi si risale per identificatore e
-- non per interpretazione. È il caso delle due "Noleggio Gonfiabili", che così si scoprono
-- essere due Calcio Balilla Umano — cosa che dal nome del pacchetto non si sarebbe mai saputa.
--
-- Poi il ripiego: dedurre dal nome del pacchetto, dove il gioco è scritto dentro. Vale per le
-- 33 restanti. "Noleggio Bubble+Archery" contiene due giochi e la prenotazione ne regge uno
-- solo: si tiene il primo, e l'Archery si perde. È una prenotazione su 35, ed è la stessa che
-- si sistemerebbe collegandole un preventivo.
--
-- Dove non c'è niente da cui ricavare il gioco la colonna resta nulla. Inventarlo sarebbe
-- peggio che lasciarlo vuoto — stessa regola già applicata alle sedi in preventivi_sede_id.sql.
-- ------------------------------------------------------------
alter table prenotazioni add column if not exists "giocoId" bigint;

-- 4a) dal preventivo collegato, per identificatore
update prenotazioni p
   set "giocoId" = (
     select g."giocoId"
       from preventivi pv
       cross join lateral jsonb_array_elements(pv.gonfiabili::jsonb) with ordinality as t(riga, ord)
       join gonfiabili g on g.id = t.riga->>'gonfiabileId'
      where pv.codice = p."preventivoCollegato"
        and jsonb_typeof(pv.gonfiabili::jsonb) = 'array'
      order by t.ord
      limit 1
   )
 where p."giocoId" is null
   and p."preventivoCollegato" is not null;

-- 4b) dal nome del pacchetto, per quelle senza preventivo
update prenotazioni p
   set "giocoId" = j.id
  from giochi j
 where p."giocoId" is null
   and j.nome = case
         when p."pacchettoNome" ilike '%bubble%'  then 'Bubble Football'
         when p."pacchettoNome" ilike '%dark%'    then 'Dark Soccer'
         when p."pacchettoNome" ilike '%archery%' then 'Archery Tag'
       end;

alter table prenotazioni drop constraint if exists prenotazioni_gioco_fk;
alter table prenotazioni add  constraint prenotazioni_gioco_fk
  foreign key ("giocoId") references giochi(id) on update cascade on delete restrict;

create index if not exists prenotazioni_gioco_idx on prenotazioni ("giocoId");

commit;

-- ------------------------------------------------------------
-- 5) DOPO — i controlli.
-- ------------------------------------------------------------

-- 5a) Il catalogo. Attesi 28 giochi, di cui 3 con per_pacchetti acceso.
select count(*) as giochi_a_catalogo,
       count(*) filter (where per_pacchetti) as giocabili_su_campo
  from giochi;

select nome, per_pacchetti from giochi where per_pacchetti order by nome;

-- 5b) Nessun gonfiabile deve essere rimasto senza gioco: questa query non deve dare righe.
select id, nome from gonfiabili where "giocoId" is null;

-- 5c) Le prenotazioni agganciate, e a quale gioco. Atteso: 2 su Calcio Balilla Umano (dai
--     preventivi), 33 su Bubble Football.
select coalesce(j.nome, '— nessun gioco ricavabile') as gioco,
       count(*) as prenotazioni,
       string_agg(distinct p."pacchettoNome", ', ') as da_quali_pacchetti
  from prenotazioni p
  left join giochi j on j.id = p."giocoId"
 group by 1
 order by 2 desc;

-- 5d) Le righe dei preventivi diventano attribuibili: quante lo sono davvero.
--     Le non attribuibili sono i preventivi vecchi senza "gonfiabileId", quelli che
--     preventivi_sede_id.sql aveva già lasciato indietro. Nessuno di loro è collegato a una
--     prenotazione, quindi non entra in nessun conto.
select count(*) filter (where g."giocoId" is not null) as righe_attribuibili,
       count(*) filter (where g."giocoId" is null)     as righe_senza_gioco,
       count(*)                                        as righe_totali
  from preventivi pv
  cross join lateral jsonb_array_elements(pv.gonfiabili::jsonb) as riga
  left join gonfiabili g on g.id = riga->>'gonfiabileId'
 where jsonb_typeof(pv.gonfiabili::jsonb) = 'array';
