-- ============================================================
-- Modulo Compensi, passo 3 — consuntivazione.
-- Schema da eseguire nell'SQL Editor di Supabase, dopo compensi.sql.
--
-- Due tabelle con ruoli diversi:
--   op_voci    ciò che il manager aggiunge a mano; esiste anche a periodo aperto
--   op_periodi la fotografia congelata al momento della consuntivazione
-- Il preventivo calcolato non si salva mai: si ricalcola dalle prenotazioni ogni volta.
-- ============================================================

-- Serve per il vincolo di non sovrapposizione più sotto (confronta interi e intervalli insieme).
create extension if not exists btree_gist;

-- ------------------------------------------------------------
-- VOCI: recensioni, spese vive, correzioni manuali.
-- Si agganciano a operatore + data, non al periodo: il manager le registra man mano,
-- quando il periodo non esiste ancora come record.
-- ------------------------------------------------------------
create table if not exists op_voci (
  id bigint generated by default as identity primary key,
  operatore text not null,                     -- utenti.username
  data date not null,                          -- giorno a cui la voce appartiene
  tipo text not null,                          -- 'recensione' | 'spesa' | 'rettifica'
  riferimento text,                            -- prenotazioni.id quando la voce riguarda una partita
  descrizione text,
  importo numeric not null default 0,          -- può essere negativo (rettifica in diminuzione)
  esente_ritenuta boolean not null default false,
  creato_il timestamptz not null default now(),
  constraint op_voci_tipo_valido check (tipo in ('recensione', 'spesa', 'rettifica'))
);
create index if not exists op_voci_operatore_data_idx on op_voci (operatore, data);

-- Una sola recensione per operatore per partita: la regola sta nel database, non solo nell'app,
-- così un doppio clic o due schede aperte non possono farne entrare due.
create unique index if not exists op_voci_una_recensione_per_partita
  on op_voci (operatore, riferimento) where tipo = 'recensione';

-- ------------------------------------------------------------
-- PERIODI: nascono solo alla consuntivazione e da lì non si toccano più.
-- L'intervallo lo sceglie il manager: un giorno di norma, più lungo quando c'è
-- un compenso concordato da ripartire.
-- ------------------------------------------------------------
create table if not exists op_periodi (
  id bigint generated by default as identity primary key,
  operatore text not null,                     -- utenti.username
  dal date not null,
  al date not null,
  -- Importo pattuito che sostituisce il calcolo a ore per questo periodo.
  -- null = vale il compenso calcolato dalle ore.
  concordato numeric,
  -- Fetta di compenso trattata come rimborso: esente da ritenuta, non aumenta il totale.
  rimborso_forfettario numeric not null default 0,
  compenso_netto numeric not null default 0,   -- quello che l'operatore incassa in mano
  ritenuta numeric not null default 0,         -- costo aggiuntivo dell'azienda, versato all'Erario
  spese numeric not null default 0,            -- rimborsi spese, esenti
  costo_azienda numeric not null default 0,    -- compenso lordizzato + forfettario + spese
  parametri jsonb not null default '{}'::jsonb, -- snapshot: ritoccare le tariffe non deve riscrivere il passato
  documento_id bigint,                         -- valorizzato quando il periodo finisce in una ricevuta
  note text,
  creato_il timestamptz not null default now(),
  constraint op_periodi_intervallo_valido check (al >= dal)
);
create index if not exists op_periodi_operatore_idx on op_periodi (operatore, dal);

-- Una giornata non può essere consuntivata due volte: due periodi dello stesso operatore
-- non possono sovrapporsi nemmeno di un giorno. È il vincolo che rende il consuntivo
-- affidabile — senza, un compenso può essere pagato due volte senza che nulla protesti.
alter table op_periodi drop constraint if exists op_periodi_no_sovrapposizioni;
alter table op_periodi add constraint op_periodi_no_sovrapposizioni
  exclude using gist (operatore with =, daterange(dal, al, '[]') with &&);
