-- ============================================================
-- Consuntivazione dei fornitori.
-- Da eseguire nell'SQL Editor di Supabase.
--
-- Il costo di un fornitore nasce preventivato: sta sulla prenotazione, nelle righe per gioco o nel
-- costo ereditato dal preventivo. Qui diventa consuntivato. Non passa dalle fatture del fornitore,
-- che non si registrano: si consuntiva un periodo, e consuntivarlo vuol dire che l'importo e' stato
-- pagato.
--
-- Stessa forma dei compensi, in tabelle gemelle e non nelle stesse: op_voci e op_periodi hanno
-- l'operatore obbligatorio e legato agli utenti, e Compensi e Costi/Ricavi le leggono dando per
-- scontato che ogni riga sia di un bubbler. Metterci un fornitore vorrebbe dire ricordarsi di
-- escluderlo ovunque, e dimenticarsene una volta sola lo manderebbe in un rimborso.
--
--   forn_voci    le rettifiche scritte a mano; esistono anche a periodo aperto
--   forn_periodi la fotografia congelata al momento della consuntivazione
--
-- Additiva: il codice in produzione non legge nessuna di queste colonne e tabelle.
-- ============================================================

begin;
set local lock_timeout = '3s';

-- ------------------------------------------------------------
-- IL CLIENTE CHE E' ANCHE FORNITORE.
-- Quando un fornitore ci commissiona un evento il suo prezzo non si incassa e non si fattura: si
-- compensa con quello che gli dobbiamo. La prenotazione dice quale sede e' il cliente, e da li'
-- finisce nella consuntivazione di quella sede invece che fra le partite da saldare e da fatturare.
-- Null = un cliente normale.
-- ------------------------------------------------------------
alter table prenotazioni add column if not exists "clienteSedeId" text;

-- Serve al vincolo di non sovrapposizione piu' sotto (confronta testo e intervalli insieme).
-- C'e' gia' se compensi_consuntivi.sql e' stato eseguito.
create extension if not exists btree_gist;

-- ------------------------------------------------------------
-- VOCI: rettifiche del costo di una partita, o del ricavo di una partita commissionata dal
-- fornitore. Si agganciano a sede + prenotazione, non al periodo, che finche' non si consuntiva
-- non esiste. Possono essere negative: uno sconto concordato e' una rettifica in diminuzione.
-- ------------------------------------------------------------
create table if not exists forn_voci (
  id bigint generated by default as identity primary key,
  sede_id text not null,                       -- sedi.id; senza foreign key, come pagamenti e fatture
  data date not null,                          -- il giorno della partita: decide in che periodo cade
  lato text not null,                          -- 'costo' (lo paghiamo noi) | 'ricavo' (ce lo deve lui)
  riferimento text not null,                   -- prenotazioni.id
  descrizione text,
  importo numeric not null default 0,          -- netto, come il costo preventivato
  creato_il timestamptz not null default now(),
  constraint forn_voci_lato_valido check (lato in ('costo', 'ricavo'))
);
create index if not exists forn_voci_sede_data_idx on forn_voci (sede_id, data);

-- ------------------------------------------------------------
-- PERIODI: nascono alla consuntivazione e da li' non si toccano piu', salvo riaprirli.
-- I totali e le righe sono congelati: se domani si ritocca il costo di una prenotazione, quello
-- che e' stato pagato non cambia da sotto. Le righe stanno in jsonb perche' sono il contenuto di
-- un consuntivo gia' chiuso: si rileggono, non ci si fanno conti.
--   righe [{ lato, riferimento, data, nominativo, descrizione, preventivato, rettifiche, consuntivato }]
-- ------------------------------------------------------------
create table if not exists forn_periodi (
  id bigint generated by default as identity primary key,
  sede_id text not null,                       -- sedi.id; senza foreign key, come pagamenti e fatture
  dal date not null,
  al date not null,
  data_consuntivo date not null default current_date,
  costo_preventivato numeric not null default 0, -- quanto dicevano le prenotazioni
  costo numeric not null default 0,              -- consuntivato: preventivato piu' rettifiche
  ricavo numeric not null default 0,             -- le partite che ci ha commissionato, compensate
  saldo numeric not null default 0,              -- costo - ricavo: positivo lo paghiamo noi
  righe jsonb not null default '[]'::jsonb,
  note text,
  creato_il timestamptz not null default now(),
  constraint forn_periodi_intervallo_valido check (al >= dal)
);
create index if not exists forn_periodi_sede_idx on forn_periodi (sede_id, dal);

-- Una giornata di un fornitore non si consuntiva due volte: e' la rete che impedisce di pagarlo
-- due volte senza che nulla protesti. Stessa regola dei periodi dei compensi.
alter table forn_periodi drop constraint if exists forn_periodi_no_sovrapposizioni;
alter table forn_periodi add constraint forn_periodi_no_sovrapposizioni
  exclude using gist (sede_id with =, daterange(dal, al, '[]') with &&);

-- Come le altre tabelle dell'app: la chiave anon deve poterle leggere e scrivere.
alter table forn_voci disable row level security;
alter table forn_periodi disable row level security;

commit;

-- Controllo: la colonna c'e' e nessuna prenotazione e' stata toccata, le tabelle sono vuote.
select count(*) as prenotazioni, count("clienteSedeId") as clienti_fornitori,
       (select count(*) from forn_voci) as voci, (select count(*) from forn_periodi) as periodi
  from prenotazioni;
