-- ============================================================
-- Modulo "Disponibilità" — schema da eseguire nell'SQL Editor di Supabase
-- ============================================================

-- Fasce orario configurabili (mattina/pomeriggio/sera)
create table if not exists disp_fasce (
  id text primary key,               -- 'mattina' | 'pomeriggio' | 'sera'
  label text not null,
  ordine int not null,
  ora_inizio time not null,
  ora_fine time not null
);
insert into disp_fasce (id, label, ordine, ora_inizio, ora_fine) values
  ('mattina', 'Mattina', 1, '06:00', '12:00'),
  ('pomeriggio', 'Pomeriggio', 2, '12:00', '18:00'),
  ('sera', 'Sera', 3, '18:00', '23:59')
on conflict (id) do nothing;

-- Anagrafica extra per i bubbler (username/ruolo/bubbler già esistono su utenti)
alter table utenti add column if not exists nome_breve text;
alter table utenti add column if not exists telefono text;
alter table utenti add column if not exists email text;

-- Disponibilità del bubbler: per campo, data e fascia. L'esistenza della riga indica disponibilità.
-- ora_inizio/ora_fine sono un eventuale override dell'orario di default della fascia.
-- Nota: utente_username e campo_id sono testo semplice, senza foreign key verso utenti/pren_campi
-- (stesso approccio già usato da pren_campi_tariffe.campoId in questo progetto): l'integrità
-- referenziale è gestita dall'app, non dal database.
create table if not exists disp_calendario (
  id bigint generated by default as identity primary key,
  utente_username text not null,
  campo_id text not null,
  data date not null,
  fascia text not null references disp_fasce(id),
  ora_inizio time,   -- null = usa l'orario di default della fascia
  ora_fine time,     -- null = usa l'orario di default della fascia
  note text,
  unique (utente_username, campo_id, data, fascia)
);
create index if not exists disp_calendario_utente_campo_idx on disp_calendario (utente_username, campo_id, data);

-- Aggiornamento di un'installazione che aveva ancora disp_campi/disp_campi_fasce e
-- disp_calendario senza campo: esegui sql/disponibilita_per_campo.sql.

-- Conferma mensile: una riga = "questo bubbler ha confermato quel mese su quel campo".
create table if not exists disp_conferme (
  id bigint generated by default as identity primary key,
  utente_username text not null,
  campo_id text not null,
  mese text not null,                                  -- 'YYYY-MM'
  confermato_il timestamptz not null default now(),
  unique (utente_username, campo_id, mese)
);
create index if not exists disp_conferme_utente_mese_idx on disp_conferme (utente_username, mese);
alter table disp_conferme disable row level security;
