-- ============================================================
-- Conferma mensile delle disponibilità
-- (da eseguire nell'SQL Editor di Supabase, dopo sql/disponibilita_per_campo.sql)
--
-- Una riga = "il bubbler X ha confermato il mese YYYY-MM sul campo Y".
-- L'esistenza della riga indica la conferma; togliendola il mese torna non confermato.
-- Nell'app la conferma si dà dall'overlay di modifica e vale su tutti i campi che
-- l'overlay sta modificando (un solo campo, oppure tutti quelli di una provincia).
-- ============================================================

create table if not exists disp_conferme (
  id bigint generated by default as identity primary key,
  utente_username text not null,
  campo_id text not null,
  mese text not null,                                  -- 'YYYY-MM'
  confermato_il timestamptz not null default now(),
  unique (utente_username, campo_id, mese)
);

create index if not exists disp_conferme_utente_mese_idx on disp_conferme (utente_username, mese);

-- Se la tabella è stata creata dal Table Editor di Supabase invece che con questo script,
-- nasce con il Row Level Security ATTIVO e senza policy: la chiave anon dell'app non può né
-- leggere né scrivere, e ogni conferma fallisce. Le altre tabelle del progetto girano con RLS
-- disattivato, quindi qui la si allinea. (Eseguirlo è innocuo se RLS era già disattivato.)
alter table disp_conferme disable row level security;
