-- ============================================================
-- Modulo "Disponibilità" — schema da eseguire nell'SQL Editor di Supabase
-- ============================================================

-- Fasce orario configurabili (mattina/pomeriggio/sera)
create table if not exists disp_fasce (
  id text primary key,               -- 'mattina' | 'pomeriggio' | 'sera'
  label text not null,
  ordine int not null,
  ora_inizio time not null,
  ora_fine time not null
);
insert into disp_fasce (id, label, ordine, ora_inizio, ora_fine) values
  ('mattina', 'Mattina', 1, '06:00', '12:00'),
  ('pomeriggio', 'Pomeriggio', 2, '12:00', '18:00'),
  ('sera', 'Sera', 3, '18:00', '23:59')
on conflict (id) do nothing;

-- Anagrafica extra per i bubbler (username/ruolo/bubbler già esistono su utenti)
alter table utenti add column if not exists nome_breve text;
alter table utenti add column if not exists telefono text;
alter table utenti add column if not exists email text;

-- Campi in cui un bubbler è disponibile a lavorare (statico, non legato a una data)
-- Nota: utente_username e campo_id sono testo semplice, senza foreign key verso utenti/pren_campi
-- (stesso approccio già usato da pren_campi_tariffe.campoId in questo progetto): l'integrità
-- referenziale è gestita dall'app, non dal database.
create table if not exists disp_campi (
  id bigint generated by default as identity primary key,
  utente_username text not null,
  campo_id text not null,
  unique (utente_username, campo_id)
);

-- Giorni della settimana in cui il bubbler è disponibile su quel campo (testo "1,3,5", 1=Lun..7=Dom,
-- stessa convenzione di pren_campi_tariffe.giorni). Colonna non più usata dall'app (sostituita dalla
-- granularità giorno+fascia di disp_campi_fasce sotto), lasciata per non perdere eventuali dati salvati.
alter table disp_campi add column if not exists giorni text;

-- Fasce (mattina/pomeriggio/sera) in cui il bubbler è disponibile su un campo, per ciascun giorno della
-- settimana (1=Lun..7=Dom). L'esistenza della riga indica disponibilità (stesso principio di disp_calendario).
create table if not exists disp_campi_fasce (
  id bigint generated by default as identity primary key,
  utente_username text not null,
  campo_id text not null,
  giorno int not null,
  fascia text not null references disp_fasce(id),
  unique (utente_username, campo_id, giorno, fascia)
);

-- Disponibilità per data + fascia, con eventuale override orario e nota
create table if not exists disp_calendario (
  id bigint generated by default as identity primary key,
  utente_username text not null,
  data date not null,
  fascia text not null references disp_fasce(id),
  ora_inizio time,   -- null = usa l'orario di default della fascia
  ora_fine time,     -- null = usa l'orario di default della fascia
  note text,
  unique (utente_username, data, fascia)
);
