-- ============================================================
-- Le fatture emesse: consuntivazione dei ricavi.
-- Da eseguire nell'SQL Editor di Supabase.
--
-- Stessa logica dei pagamenti: una prenotazione o un voucher possono avere N fatture, e il
-- legame e' tipo + riferimento, senza foreign key (come pagamenti: l'integrita' la tiene l'app).
--
-- Si salvano data, numero e importo lordo -- lo stesso lordo dei pagamenti, cosi' si confrontano
-- senza conversioni. Il numero e' testo perche' una serie ("246/A") non e' un numero.
--
-- "origine" dice se la riga e' stata scritta a mano o arriva dall'export di Fatture in Cloud: in
-- caso di dubbio sull'abbinamento e' la prima cosa che si vuole sapere.
--
-- Il vincolo di unicita' rende l'import ripetibile: la stessa fattura sulla stessa prenotazione
-- non entra due volte, anche se l'export si carica di nuovo.
-- ============================================================

begin;
set local lock_timeout = '3s';

create table if not exists fatture (
  id bigint generated by default as identity primary key,
  tipo text not null check (tipo in ('prenotazione', 'voucher')),
  riferimento text not null,                 -- prenotazioni.id oppure voucher.codice
  data date not null,
  numero text not null,
  importo numeric(10,2) not null check (importo > 0),
  origine text not null default 'manuale' check (origine in ('manuale', 'import')),
  creato_il timestamptz not null default now()
);

create index if not exists fatture_tipo_riferimento_idx on fatture (tipo, riferimento);
create unique index if not exists fatture_unica_idx on fatture (tipo, riferimento, numero, data);

-- Come le altre tabelle dell'app: la chiave anon deve poterla leggere e scrivere.
alter table fatture disable row level security;

commit;

-- Controllo: la tabella c'e' ed e' vuota.
select count(*) as fatture from fatture;
