-- ============================================================
-- Tabella unica dei pagamenti — schema da eseguire nell'SQL Editor di Supabase
-- Sostituisce la colonna jsonb prenotazioni.pagamenti ed è usata anche dai voucher.
-- ============================================================

-- tipo/riferimento sono testo semplice, senza foreign key verso prenotazioni/voucher
-- (stesso approccio già usato da pren_campi_tariffe.campoId e disp_campi in questo progetto):
-- l'integrità referenziale è gestita dall'app, non dal database.
create table if not exists pagamenti (
  id bigint generated by default as identity primary key,
  tipo text not null,                       -- 'prenotazione' | 'voucher'
  riferimento text not null,                -- prenotazioni.id oppure voucher.codice
  data date not null,
  importo numeric not null default 0,
  nominativo text,
  creato_il timestamptz not null default now()
);
create index if not exists pagamenti_tipo_riferimento_idx on pagamenti (tipo, riferimento);

-- Migrazione una tantum dei pagamenti finora salvati nella colonna jsonb prenotazioni.pagamenti.
-- Ripetibile senza duplicare: salta le prenotazioni che hanno già righe in pagamenti.
insert into pagamenti (tipo, riferimento, data, importo, nominativo)
select 'prenotazione', p.id, (x->>'data')::date, coalesce((x->>'importo')::numeric, 0), nullif(x->>'nominativo', '')
from prenotazioni p, lateral jsonb_array_elements((p.pagamenti)::jsonb) as x
where jsonb_typeof((p.pagamenti)::jsonb) = 'array'
  and coalesce(x->>'data', '') <> ''
  and not exists (select 1 from pagamenti pg where pg.tipo = 'prenotazione' and pg.riferimento = p.id);

-- La colonna prenotazioni.pagamenti non viene più né letta né scritta dall'app: resta come backup
-- dei dati pre-migrazione e può essere eliminata a mano quando non serve più
-- (alter table prenotazioni drop column pagamenti;).

-- Voucher usato a saldo, totale o parziale, di una prenotazione: il legame sta sulla prenotazione e
-- il valore del voucher vale di per sé come pagamento (non genera una riga in pagamenti).
alter table prenotazioni add column if not exists "voucherCodice" text;

-- Stato pagamento anche sui voucher ('in attesa' | 'acconto' | 'saldato'), come già su prenotazioni.
alter table voucher add column if not exists "statoPagamento" text;
